config = {
'num_rounds': 100,                  
'proportion': 0.2,                 
'learning_rate_decay': 0.998,        
'lr_scheduler': -1,
'early_stop': -1,                  
'num_epochs': 1,                      
'num_steps': -1,                   
'batch_size': 64,
'learning_rate': 1e-5,
'optimizer': 'AdamW',               
'clip_grad': 0.0,
'momentum': 0.0,
'weight_decay': 0.0,
'algo_para': [],                    
'sample': 'uniform',                
'aggregate': 'other',                
'train_holdout': 0.0,                
'test_holdout': 0,                    
'local_test': False,                  
'seed': 0,                             
'dataseed': 0,                                
'gpu': [0, 1, 2, 3],             
'server_with_cpu': False,             
'num_parallels': 4,              
'num_workers': 0,                      
'pin_memory': False,
'test_batch_size': 64,               
'log_file': True,
'no_log_console': True,
'eval_interval': 1,                          
'model': 'cnn',
'model_hetero': False,
'client_test_only': False
}